/*
 * spi_protocol.h
 *
 * Created: 14.06.2016 14:44:17
 *  Author: martin
 */ 


#ifndef SPI_PROTOCOL_H_
#define SPI_PROTOCOL_H_

#define	SPI_CMD_EULER_COORD_BATT	0x02
#define	SPI_CMD_EULER_COORD_BATT_NUM_BYTES	9
#define SPI_CMD_EULER_COORD_BATT_DIAG 0x05
#define SPI_CMD_EULER_COORD_BATT_DIAG_NUM_BYTES 16
#define	SPI_CMD_SET_WRITE	0x28
#define	SPI_CMD_SET_WRITE_NUM_BYTES	5
#define SPI_CMD_MOTOR_DEBUG	0x99
#define	SPI_CMD_MOTOR_DEBUG_NUM_BYTES	8





#endif /* SPI_PROTOCOL_H_ */